title: Sam Maule
author:
  name: Sam Maule
description: Machine learning engineering and climate tech.
markdown: kramdown
plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
permalink: /blog/:year/:month/:day/:title
google_analytics: UA-136966343-1
htmlwidgets: true
url: https://maule.io
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/sammaule" }
    - { platform: twitter, user_url: "https://twitter.com/SEMaule" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/sam-maule-08b0a935/" }
disqus:
  shortname: maule-1
